import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='max-w-6xl  mx-auto'>
          {/* Nav bar */}
          <nav className='flex py-5 bg-red-1'>
            <div className='flex gap-4'>
              <Link className='text-4xl font-semibold px-4 text-[#f13a01]' href={'/'}>Crave Slice</Link>
              <div className='text-2xl text-slate-700 flex justify-evenly gap-6'>
                <Link href={'/'}>Home</Link>
                <Link href={'/'}>Menu</Link>
                <Link href={'/'}>About</Link>
                <Link href={'/'}>Contact</Link>
              </div>
            </div>
            {/* <div className='text-end'>
              <Link className='text-end' href={'/'}>Login</Link>
            </div> */}
          </nav>
          {children}
        </div>
      </body>
    </html>
  )
}
