import { Inter } from 'next/font/google'
import './globals.css'

import { AuthProvider } from './provider'
import Navbar from '../../src/component/Navbar'
import Footer from '../../src/component/Footer'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <div className='max-w-6xl  mx-auto'>
            <Navbar></Navbar>
            {children}
            < Footer></Footer>
          </div>
        </AuthProvider>

      </body>
    </html>
  )
}
